version: "3.9"
services:
  redis:
    container_name: redis-vss-py
    image: redis/redis-stack:7.2.0-M01
    volumes:
      - ./redisdata:/data
    environment:
      - REDIS_ARGS=--appendonly yes --save ""
    ports:
      - "6379:6379"
      - "8001:8001"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure